import { QuerySchema } from "./sqlSchema.js";

/** Generate a Typescript definition file for the query */
export function generateDts(schema: QuerySchema): string {
  let outputType =
    schema.outputFields.length > 0
      ? `export type OutputType = {\n${schema.outputFields
          .map((field) => {
            return `  ${field.name}: ${field.type}${
              field.nullable ? ` | null` : ``
            };\n`;
          })
          .join("")}}`
      : ``;
  return `// Auto-generated by vite-plugin-sqlite
${outputType}
export default async function(): Promise<${
    outputType ? "OutputType[]" : "void"
  }>;
`;
}
